image_dir: "images/images/"
output_raw_dir : "images/output_raw_images/"
output_bin_dir : "images/output_bin_images/"
bbox_output_dir: "images/bbox/"
arm_mask_output_dir: "images/arm_mask_output_dir/"
unit_mask_output_dir: "images/unit_mask_output_dir/"
merge_vis_dir: "images/merge_vis_dir/"
Annotation:
  HandType : 3  # 左手 ： 1, 右手 ： 3
  ArmType : 4 # 左手臂 : 2, 右手臂 : 4