image_dir: "datasets/images/"
annotation_dir: "output/annotation"
sub_yaml_dir: "output/images/"

output_dir_name:
  User: "Lucas"
  sleeve: "white"
  gesture_id: 10
  angle_id: 2 # 手背 : 0, 90度 : 1, 180度 : 2
  hand_id: right  # 右手 : right, 左手 : left

output_dir:
  dir: "output/images/{}"
  raw_dir : "output/images/{}/RawImages"
  bin_dir : "" # "images/{}/{}/{}/BinImages/"
  contrast_dir : "output/vis/{}/Contrast"
  bbox_dir: "" #"images/{}/{}/{}/BboxImages/"
  hand_arm_mask_dir: "" #"images/{}/{}/{}/HandArmMask/"
  unit_mask_dir: "output/mask/{}/UnitMask"
  merge_vis_dir: "output/vis/{}/res"

Annotation:
  HandType : 3  # 左手 ： 1, 右手 ： 3
  ArmType : 4 # 左手臂 : 2, 右手臂 : 4
  accessories:
    left_hand_accessories: False
    right_hand_accessories: False
    left_arm_accessories: False
    right_arm_accessories: False

"camera":
  "id" : 0,
  "retify" : false,
  "width": 640,
  "height": 400

image_filter:
  contrast :
    alpha: 2
    beta: 0
  binarize:
    threshold: 47
  erosion:
    kernel: 3
    iter: 1
  medianBlur:
    kernel: 5