image_dir: "images/images/"
annotation_json: "images"

Class_param:
  User: "Lucas"
  gesture_id: 1
  angle_id: 1    # 手背 : 0, 90度 : 1, 180度 : 2

output_dir:
  dir: "images/{}/{}/{}"
  raw_dir : "images/{}/{}/{}/RawImages"
  bin_dir : "" # "images/{}/{}/{}/BinImages/"
  contrast_dir : "images/{}/{}/{}/Contrast"
  bbox_dir: "" #"images/{}/{}/{}/BboxImages/"
  hand_arm_mask_dir: "" #"images/{}/{}/{}/HandArmMask/"
  unit_mask_dir: "images/{}/{}/{}/UnitMask"
  merge_vis_dir: "images/{}/{}/{}/Vis"

Annotation:
  HandType : 3  # 左手 ： 1, 右手 ： 3
  ArmType : 4 # 左手臂 : 2, 右手臂 : 4
  left_hand_accessories: False
  right_hand_accessories: False
  left_arm_accessories: False
  right_arm_accessories: False

contrast :
  alpha: 2
binarize: 55
erosion:
  kernel: 3
  iter: 1
medianBlur:
  kernel: 5